### ISSUE TITLE
Requesting move repository to TulipCharts

### ISSUE THREAD

**Issue by G8XSU** [TulipCharts/tulipy#37]
To provide consistent interface to general users and better maintainability. 

Please consider moving this repository to Org TulipCharts i.e TulipCharts/tuliPy

**Comment by cirla** [comment]
@codeplea has expressed interest in maintaining this. I will move the GitHub repo and the PyPI project under his control.

**Comment by codeplea** [comment]
This has been completed. This repo is now officially homed at https://github.com/TulipCharts/tulipy
